Name changes for squisher

diff --git a/releasetools/squisher b/releasetools/squisher
--- a/releasetools/squisher
+++ b/releasetools/squisher
@@ -19,8 +19,8 @@ else
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-	echo "ERROR: $0 only works with a full build environment. $OUT should exist."
-	exit 1
+    echo "ERROR: $0 only works with a full build environment. $OUT should exist."
+    exit 1
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
@@ -31,42 +31,42 @@ else
     OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
 fi
 if [ ! -f "$OTAPACKAGE" ]; then
-	echo "$OTAPACKAGE doesn't exist!";
-	exit 1
+    echo "$OTAPACKAGE doesn't exist!";
+    exit 1
 fi
 
-OPTICHARGER=$ANDROID_BUILD_TOP/vendor/aokp/tools/opticharger
+OPTICHARGER=$ANDROID_BUILD_TOP/vendor/BlackICE/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
 
 # Some products want a squashfs for xbin for space
 case "$TARGET_PRODUCT" in
-	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
-	*) WANT_SQUASHFS=0 ;;
+    cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+    *) WANT_SQUASHFS=0 ;;
 esac
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
-	fatal=0
-	MKSQUASHFS_VER_REQ=4
-	if type mksquashfs >/dev/null 2>&1; then
-		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
-			echo
-			echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
-			fatal=1
-		fi
-	else
-		echo
-		echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
-		fatal=1
-	fi
+    fatal=0
+    MKSQUASHFS_VER_REQ=4
+    if type mksquashfs >/dev/null 2>&1; then
+        if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+            echo
+            echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
+            fatal=1
+        fi
+    else
+        echo
+        echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
+        fatal=1
+    fi
 
-	if [ "$fatal" -ne 0 ]; then
-		echo
-		echo "       Unoptimized package is still available at"
-		echo "         $OTAPACKAGE"
-		exit $fatal
-	fi
+    if [ "$fatal" -ne 0 ]; then
+        echo
+        echo "       Unoptimized package is still available at"
+        echo "         $OTAPACKAGE"
+        exit $fatal
+    fi
 fi
 
 REPACK=$OUT/repack.d
@@ -93,39 +93,39 @@ find ./ -name \*.apk | $XARGS $OPTICHARGER
 rm $REPACK/ota/system/app/Launcher2.apk
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
-	squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
-	updater=$REPACK/ota/META-INF/com/google/android/updater-script
+    squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
+    updater=$REPACK/ota/META-INF/com/google/android/updater-script
 
-	# Relocate su
-	cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
-	rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
-	mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
-	chmod -R 555 $REPACK/_xbin/*
+    # Relocate su
+    cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
+    rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
+    mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
+    chmod -R 555 $REPACK/_xbin/*
 
-	# Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
-	# Forgive me for the regex hell here. 
-	ln -s ../bin/su $REPACK/_xbin/su
-	for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
-	do
-		ln -s busybox $REPACK/_xbin/$link
-	done
+    # Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
+    # Forgive me for the regex hell here.
+    ln -s ../bin/su $REPACK/_xbin/su
+    for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
+    do
+        ln -s busybox $REPACK/_xbin/$link
+    done
 
-	# Create the squashfs with new and improved symlinkage!
-	mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
-	rm -rf $REPACK/ota/system/xbin/*
-	mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
-	chmod 444 $REPACK/ota/system/xbin/xbin.sqf
+    # Create the squashfs with new and improved symlinkage!
+    mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
+    rm -rf $REPACK/ota/system/xbin/*
+    mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
+    chmod 444 $REPACK/ota/system/xbin/xbin.sqf
 
-	# Remove xbin stuff and fix up updater-script
-	$SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
+    # Remove xbin stuff and fix up updater-script
+    $SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
 fi
 
 
 # Fix build.prop
 $SED -i \
-	-e '/ro\.kernel\.android\.checkjni/d' \
-	-e '/ro\.build\.type/s/eng/user/' \
-	$REPACK/ota/system/build.prop
+    -e '/ro\.kernel\.android\.checkjni/d' \
+    -e '/ro\.build\.type/s/eng/user/' \
+    $REPACK/ota/system/build.prop
 
 
 # Delete unnecessary binaries
@@ -139,12 +139,12 @@ rm -rf $REPACK/ota/recovery
 
 # Strip modules
 [ -d $REPACK/ota/system/lib/modules ] && \
-	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
+    find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
 
 # Determine what to name the new signed package
 
 #MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
-VERSION=`cat "vendor/aokp/configs/common_versions.mk" | grep ro.aokp.version | head -1 | cut -f2 -d '=' | cut -f3 -d '_'`
+VERSION=`cat "vendor/BlackICE/configs/common_versions.mk" | grep ro.blackice.version | head -1 | cut -f2 -d '=' | cut -f3 -d '_'`
 MODVERSION="$TARGET_PRODUCT"_"$VERSION"
 REALDATE=`date +%F-%H_%M`
 OUTFILE=$OUT/$MODVERSION-$REALDATE.zip
@@ -156,9 +156,9 @@ echo
 printf "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
 java -Xmx2048m \
-	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-	$REPACK/update.zip $OUTFILE
+    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
+    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+    $REPACK/update.zip $OUTFILE
 echo
 printf "Cleaning up..."
 rm -rf $REPACK
